# 2.1) Use uma imagem Node na versão lts-alpine3.19 como base
FROM node:lts-alpine3.19

# 2.2) Utilize o usuário node para executar a aplicação
USER node

# 2.3) Defina o diretório de trabalho como: /app-money
WORKDIR /app-money

# 2.4) Copie todos os diretórios e arquivos da sua aplicação para o Container
COPY . .

# 2.5) Exponha a porta adequada para que a aplicação seja acessível
EXPOSE 3000

# 2.6) Configure o comando padrão para executar seu App NodeJS.
CMD ["node", "app.js"]